#!/usr/bin/env python

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

get_ipython().run_line_magic('matplotlib', 'inline')
Location = "C:/Users/camil/OneDrive/Bureau/datasets/axisdata.csv"
df = pd.read_csv(Location)

#Histogram of Cars Sold by Sales Training
df.hist(column = 'Cars Sold', by = 'SalesTraining')

#Box Plot of Cars Sold by Gender
df1 = pd.DataFrame(data = df, columns=['Years Experience', 'Cars Sold',
'Gender'])
df1.boxplot(by='Gender',column='Cars Sold')

#Average cars sold per month
df['Cars Sold'].mean()

#Max cars sold per month
df['Cars Sold'].max()

#Min cars sold per month
df['Cars Sold'].min()

#Average years of experience
df['Years Experience'].mean()

#Average cars sold per month by gender
df.loc[df['Gender'] == 'F']['Cars Sold'].mean()
df.loc[df['Gender'] == 'M']['Cars Sold'].mean()

#Average hours worked by people selling more than three cars per month
df.loc[df['Cars Sold'] > 3]['Cars Sold'].mean()

#Average years of experience for people selling more than three cars per month
df.loc[df['Cars Sold'] > 3]['Years Experience'].mean()

#Average cars sold per month sorted by whether they have had sales training
df.loc[df['SalesTraining'] == 'N']['Cars Sold'].mean()
df.loc[df['SalesTraining'] == 'Y']['Cars Sold'].mean()
