#!/usr/bin/env python
# coding: utf-8

# In[23]:


import pandas as pd
import numpy as np
Location = "C:/Users/camil/OneDrive/Bureau/gradedata.csv"
df = pd.read_csv(Location)

df['timegmgt'] = np.where((df['exercise']>3) & (df['hours']>17),'Yes','No')

