#!/usr/bin/env python
# coding: utf-8

# In[15]:


import pandas as pd
Location = "C:/Users/camil/OneDrive/Bureau/gradedata.csv"
df = pd.read_csv(Location)

#create the bin dividers
bins = [0,80,100]

#create the names for the groups
group_names = ["Pass","Fail"]

df['passOrFail'] = pd.cut(df['grade'],bins,labels=group_names)

df.head()

