#!/usr/bin/env python

import matplotlib.pyplot as plt
import pandas as pd
get_ipython().run_line_magic('matplotlib', 'inline')
Location = "C:/Users/camil/OneDrive/Bureau/gradedata.csv"
df = pd.read_csv(Location)

df.hist(column="age", by="gender")
