#!/usr/bin/env python

import pandas as pd
import numpy as np

Location = \"C:/Users/camil/OneDrive/Bureau/gradedata.csv\"
df = pd.read_csv(Location)

import statsmodels.formula.api as sm

result = sm.ols(\n",
 	   formula='grade ~ age + exercise + hours',
     data=df).fit()
     
result.summary()
