#!/usr/bin/env python

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
Location = "C:/Users/camil/OneDrive/Bureau/gradedata.csv"
df = pd.read_csv(Location)

plt.scatter(df['hours'], df['grade'])
