#!/usr/bin/env python

import pandas as pd
Location = \"C:/Users/camil/OneDrive/Bureau/gradedata.csv\"
df = pd.read_csv(Location)

df = df.sort_values(by=['lname','fname','age','grade'],
                      ascending=[True,True,True,True])
   
df
